### ISSUE TITLE
Support file pattern

### ISSUE THREAD

**Issue by bjornbouetsmith** [vers-one/dotnet-project-version-updater#1]
Hi,

I am trying to use this action in github, but I would like to update multiple project files in one single go - so it would be awesome if you could support a pattern of files instead of just a single file.

i.e.:

~~~yaml
name: Update version
      uses: vers-one/dotnet-project-version-updater@v1.0
      with:
        file: Source/**/*.csproj
        version: bump-build
~~~

If you do not want to break the interface and do not want to detect if its a pattern - you could introduce a`files` field instead.

Thanks

**Comment by bjornbouetsmith** [comment]
Does this mean that you will improve this?

If so - then awesome - I will really look forward to it, since I intend to use this on my ci-builds - and on solutions with many projects, its a pain in the ass to have multiple statements where only the project name is different.

Thanks

**Comment by vers-one** [comment]
@bjornbouetsmith, yes, I'm working on this and a few other enhancements. It should be ready approximately at the end of this week.

**Comment by bjornbouetsmith** [comment]
Awesome- if you are changing it already - how about you also support that you can set a .props file as the target of this.

I tried making a Directory.Build.props file - which is just a "normal" project file, but my build failed with:
~~~
Error: Unsupported file type for file: Source/Directory.Build.props
~~~

Example of how it can look:
~~~xml
<Project>
  <PropertyGroup>
    <Version>1.1.4</Version>
    <PackageVersion>$(Version)</PackageVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net6.0</TargetFramework>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
  </PropertyGroup>
</Project>
~~~

**Comment by vers-one** [comment]
Sure, I'll do this.

**Comment by vers-one** [comment]
Implemented in v1.1. Please let me know if it works for your project.

**Comment by bjornbouetsmith** [comment]
> Implemented in v1.1. Please let me know if it works for your project.

Wildcard patterns work, but using a directory.props file does not work - I still get:
Unsupported file type for file: Source/Directory.Build.props

I was under the impression that you would make support for props files as well?

**Comment by bjornbouetsmith** [comment]
Or do you want another Issue specificly for that?

**Comment by vers-one** [comment]
For some reason I thought it's `Directory.Build.prop` 🤦‍♂️
Could you try it again with v1.2?

**Comment by bjornbouetsmith** [comment]
> For some reason I thought it's `Directory.Build.prop` 🤦‍♂️ Could you try it again with v1.2?

Sure :-) Thanks

To make it more future proof - you could just ignore the type of file - and just use whatever pattern people use.

Then you could
foreach(var file in files)
{
  // Replace <Version> if there
}
Fail if no files/Version tags were replaced in the file found by the pattern.

Then people can use whatever type of file, as long as it contains a <Version>1.2.3</Version>

Its just a suggestion :-)

**Comment by vers-one** [comment]
Yeah, I thought about that. Unfortunately, .NET Framework projects store their versions in AssemblyInfo.cs files (or some other *.cs files) which have a different way of declaring versions:
```
[assembly: AssemblyVersion("1.2.3")]
[assembly: AssemblyFileVersion("1.2.3")]
```

Of course, I could just search for all known patterns in all specified files but that increases the risk of an unwanted change if some part of the file matched the version pattern accidentally.

**Comment by bjornbouetsmith** [comment]
Success:
Source/Directory.Build.props: version updated from 1.1.3 to 1.1.4

**Comment by bjornbouetsmith** [comment]
So thank you very much :-) You can close the issue.

**Comment by vers-one** [comment]
Thank you for checking this!
