### ISSUE TITLE
Other .NET languages support

### ISSUE THREAD

**Issue by picolino** [vers-one/dotnet-project-version-updater#3]
Package name `dotnet-project-version-updater` leads us to be used not only with C# projects, but also with other dotnet family languages, like VisualBasic, F# etc.

But for now we don't have F# or VB support by this package.

Don't know about VB, but `.fsproj` files are pretty similar with `.csproj` files especially in version attributes.

So it will be cool if at least `.fsproj` support will be added.

**Comment by vers-one** [comment]
Implemented in v1.3.
