### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by ihctoag** [vers-one/dotnet-project-version-updater#6]
Hi,

github actions shows following warning after the build:

Node.js 16 actions are deprecated. 
Please update the following actions to use Node.js 20: vers-one/dotnet-project-version-updater@v1.3. 
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

best regards
Tom

**Comment by vers-one** [comment]
Thanks! Updated Node.js version to 20 in 1.4 release.
