### ISSUE TITLE
is it possible to set AssemblyInformationalVersion

### ISSUE THREAD

**Issue by taooceros** [vers-one/dotnet-project-version-updater#9]

**Comment by vers-one** [comment]
I can add support for `AssemblyInformationalVersion` attribute, but as far as I know, the value of this attribute usually represents the version of the whole product and many people tend to prefer to set it manually.

**Comment by vers-one** [comment]
Implemented in [version 1.6](https://github.com/vers-one/dotnet-project-version-updater/releases/tag/v1.6).

The list of all added tags and attributes can be found in the description of the PR https://github.com/vers-one/dotnet-project-version-updater/pull/12.
